# Generated by Django 4.0.2 on 2022-03-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0002_alter_upload_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='Owner',
        ),
    ]
