# Generated by Django 4.0.2 on 2022-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0003_remove_upload_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_key', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
