# Generated by Django 4.0.2 on 2022-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0003_alter_upload_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Files',
            field=models.FileField(unique=True, upload_to=''),
        ),
    ]
