# Generated by Django 4.0.2 on 2022-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0004_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='dec_key',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
