# Generated by Django 4.0.2 on 2022-03-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0005_alter_download_dec_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='file_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
