# Generated by Django 4.0.2 on 2022-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extendedcloudapp', '0006_download_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='download',
            name='dec_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
